version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    container_name: pendragon-nginx-development
    entrypoint: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '80:80'
      - '443:443'
  pendragon-api-development:
    # network_mode: 'host'
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - '5000:5000'
    container_name: pendragon-api-development
    volumes:
      - ./:/usr/src/app/api
      - ./node_modules:/usr/src/app/api/node_modules
    environment:
      PORT: '${PORT}'
      MONGO: '${MONGO}'
      NODE_ENV: '${NODE_ENV}'
      TOKEN_SECRET: '${TOKEN_SECRET}'
      REFRESH_TOKEN_SECRET: '${REFRESH_TOKEN_SECRET}'
      SMS_SID: '${SMS_SID}'
      SMS_AUTH_TOKEN: '${SMS_AUTH_TOKEN}'
      EMAIL_ID: '${EMAIL_ID}'
      EMAIL_PASSWORD: '${EMAIL_PASSWORD}'
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    container_name: pendragon-mongodb-development
    environment:
      MONGO_INITDB_DATABASE: pendragon
    volumes:
      - ./data:/data/db
  pendragon-webapp-development:
    build:
      context: ./web/
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
    container_name: pendragon-webapp-development
    stdin_open: true
    volumes:
      - ./web/:/usr/src/app/webapp
      - ./web/node_modules:/usr/src/app/webapp/node_modules
