version: '3.3'
services:
  pendragon-api:
    build: ./
    environment:
      PORT: '${PORT}'
      MONGO: '${MONGO}'
      NODE_ENV: '${NODE_ENV}'
      TOKEN_SECRET: '${TOKEN_SECRET}'
      REFRESH_TOKEN_SECRET: '${REFRESH_TOKEN_SECRET}'
      SMS_SID: '${SMS_SID}'
      SMS_AUTH_TOKEN: '${SMS_AUTH_TOKEN}'
    ports:
      - '5000:5000'
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Zg134yi#e0p0s
      MONGO_INITDB_DATABASE: pendragon
    volumes:
      - /mongo/data:/data/db
