version: '3.3'
services:
  pendragon-api:
    build: ./
    ports:
      - '5000:5000'
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Zg134yi#e0p0s
      MONGO_INITDB_DATABASE: pendragon
    volumes:
      - /mongo/data:/data/db
