version: '3.3'
services:
  certbot:
    image: certbot/certbot
    volumes:
      - ./security/certbot/conf:/etc/letsencrypt
      - ./security/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  nginx:
    restart: always
    build:
      context: ./web
    entrypoint: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - ./security/nginx:/etc/nginx/conf.d
      - ./security/certbot/conf:/etc/letsencrypt
      - ./security/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
  pendragon-api:
    build: ./
    environment:
      PORT: '${PORT}'
      MONGO: '${MONGO}'
      NODE_ENV: '${NODE_ENV}'
      TOKEN_SECRET: '${TOKEN_SECRET}'
      REFRESH_TOKEN_SECRET: '${REFRESH_TOKEN_SECRET}'
      SMS_SID: '${SMS_SID}'
      SMS_AUTH_TOKEN: '${SMS_AUTH_TOKEN}'
    ports:
      - '5000:5000'
    network_mode: 'host'
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Zg134yi#e0p0s
      MONGO_INITDB_DATABASE: pendragon
    volumes:
      - /mongo/data:/data/db
